// Generated by CoffeeScript 1.12.4
var Event, EventEmitter, Type, assertType, keyModifiers, type;

EventEmitter = require("events").EventEmitter;

assertType = require("assertType");

Event = require("Event");

Type = require("Type");

keyModifiers = "ctrl meta shift".split(" ");

type = Type("KeyEmitter");

type.defineValues(function() {
  return {
    _didPressKey: Event(),
    _emitter: null
  };
});

type.defineGetters({
  didPressKey: function() {
    return this._didPressKey.listenable;
  }
});

type.defineMethods({
  send: function(data) {
    assertType(data, String);
    return this._emitter.emit("data", data);
  },
  _keypress: function(char, key) {
    var command, modifier;
    command = key ? key.name : char;
    if (modifier = this._getModifier(key)) {
      command += "+" + modifier;
    }
    this._didPressKey.emit({
      char: char,
      key: key,
      command: command,
      modifier: modifier
    });
  },
  _getModifier: function(key) {
    var i, len, modifier;
    for (i = 0, len = keyModifiers.length; i < len; i++) {
      modifier = keyModifiers[i];
      if (key[modifier]) {
        return modifier;
      }
    }
    return null;
  },
  _setupStream: function(stream) {
    var keypress;
    if (this._emitter) {
      return;
    }
    if (stream && stream.isTTY) {
      stream.setRawMode(true);
      keypress = require("keypress");
      keypress((function(_this) {
        return function() {
          var emitter;
          _this._emitter = emitter = new EventEmitter;
          emitter.on("keypress", _this._keypress.bind(_this));
          emitter.write = function(chunk) {
            return stream.write(chunk);
          };
          return emitter;
        };
      })(this)());
    }
  }
});

module.exports = type.construct();
